import type { Language } from "./i18n";

const en = {
  personalInfo: {
    name: "Furkan Ağlar",
    title: "QA Engineer | WordPress Developer | AI-Assisted Full-Stack Developer",
    location: "Denizli, Turkiye",
    tagline: "Open to Remote & Relocation",
    email: "furkan-aglar@outlook.com",
    website: "furkanaglar.com",
    linkedin: "linkedin.com/in/furkanaglar",
    linkedinUrl: "https://linkedin.com/in/furkanaglar",
  },
  quickFacts: ["QA Engineer", "WordPress Developer", "Next.js Developer", "DevOps", "Vibe Coder"],
  about: {
    summary:
      "QA Engineer and Full-Stack Developer with a unique blend of quality assurance expertise and hands-on development skills. I transform design concepts into polished, production-ready applications while maintaining rigorous quality standards. My experience spans WordPress theme and plugin development, modern full-stack frameworks like Next.js, and AI-assisted development workflows.",
    strengths: [
      "QA mindset combined with development execution—catching issues before they reach production",
      "Seamless Figma-to-production pipeline with pixel-perfect implementation",
      "WordPress mastery: 40+ Elementor demo sites, custom themes, plugins, optimization, and enterprise-level support",
      "AI-assisted development and prompt engineering for accelerated delivery",
      "DevOps fundamentals: VPS management, CI/CD, monitoring, and infrastructure optimization",
    ],
    education: {
      institution: "Sinop University",
      degree: "Associate Degree in Computer Networks and Internet Technologies",
      period: "Sep 2019 – Jun 2021",
      gpa: "3.62",
    },
    languages: [
      { name: "Turkish", level: "Native" },
      { name: "English", level: "B1" },
      { name: "German", level: "A1" },
    ],
  },
  experience: [
    {
      id: "exp-1",
      title: "QA Engineer & AI-Assisted Software Developer",
      company: "OctaSys",
      location: "Remote",
      period: "Jun 2025 – Feb 2026",
      achievements: [
        "Spearheading quality assurance processes across web and mobile applications, ensuring zero critical bugs reach production",
        "Building and maintaining automated test suites to accelerate release cycles",
        "Developing full-stack features using AI-assisted workflows and modern frameworks",
        "Collaborating with cross-functional teams to define quality standards and testing strategies",
        "Conducting thorough code reviews with a focus on performance, security, and maintainability",
      ],
    },
    {
      id: "exp-2",
      title: "Project Manager",
      company: "OctaSys",
      location: "Remote",
      period: "Sep 2024 – Jun 2025",
      achievements: [
        "Led end-to-end project delivery for multiple client engagements, coordinating development, design, and QA teams",
        "Implemented Agile workflows and sprint planning, improving team velocity by 30%",
        "Acted as primary technical liaison between clients and development teams",
        "Managed project timelines, budgets, and resource allocation for simultaneous projects",
        "Established documentation standards and knowledge-sharing practices",
      ],
    },
    {
      id: "exp-3",
      title: "Frontend WordPress Developer & Support Engineer",
      company: "OctaSys",
      location: "Remote",
      period: "Nov 2021 – Sep 2024",
      achievements: [
        "Built 40+ Elementor-powered WordPress demo sites and production pages across SaaS, hotel, ecommerce, agency, architecture, AI product, and food industry categories",
        "Developed 25+ custom WordPress themes and plugins from Figma designs, achieving 100% client satisfaction",
        "Provided technical support for 50+ WordPress sites, resolving complex issues within 24-hour SLA",
        "Optimized site performance, achieving 90+ PageSpeed scores and sub-2-second load times",
        "Implemented SEO best practices, improving organic traffic by 40% across client portfolio",
        "Mentored junior developers on WordPress best practices and front-end technologies",
        "Managed hosting infrastructure, backups, security hardening, and uptime monitoring",
      ],
    },
    {
      id: "exp-4",
      title: "WordPress Developer (Intern)",
      company: "DYT Biotechnology R&D",
      location: "Denizli, Turkiye",
      period: "Jul 2021 – Aug 2021",
      achievements: [
        "Designed and developed a corporate WordPress website from concept to launch",
        "Collaborated with stakeholders to define requirements and deliver within tight deadlines",
        "Gained hands-on experience with WordPress theme customization and plugin integration",
      ],
    },
  ],
  projects: [
    {
      id: "proj-1",
      title: "Modsy.io",
      role: "Founder & Full-Stack Developer",
      period: "Nov 2025 – Present",
      summary:
        "A SaaS platform for gamers to create, share, and download custom game modifications. Built with modern full-stack technologies and achieved viral growth in the first week.",
      impact: "2,500+ downloads in the first week",
      stack: [
        "Next.js",
        "React",
        "TypeScript",
        "Node.js",
        "Prisma",
        "MySQL/MariaDB",
        "Tailwind CSS",
        "VPS",
        "Object Storage",
        "CDN",
        "PM2",
        "Git",
        "SEO",
      ],
      highlights: [
        "Architected and deployed a scalable full-stack application on VPS infrastructure",
        "Implemented secure authentication, file uploads with object storage, and CDN integration",
        "Optimized for SEO with server-side rendering and metadata management",
        "Achieved 2,500+ downloads within the first week of launch",
      ],
      link: "https://modsy.io",
      caseStudyLink: "#",
      category: ["Next.js", "Full-Stack", "DevOps", "SEO"],
    },
    {
      id: "proj-2",
      title: "Frkn64 Modding",
      role: "Founder & WordPress Developer",
      period: "Mar 2016 – Present",
      summary:
        "A community-driven platform for Nintendo 64 game modifications. Managed all aspects of the site including development, hosting, performance optimization, and content strategy.",
      impact: "~50,000 monthly visitors, tens of thousands of downloads",
      stack: [
        "WordPress",
        "PHP",
        "MySQL",
        "JavaScript",
        "HTML/CSS",
        "VPS Hosting",
        "Cloudflare CDN",
        "SEO",
      ],
      highlights: [
        "Built and maintained a high-traffic WordPress platform from the ground up",
        "Optimized for search engines, achieving top Google rankings for niche keywords",
        "Managed full hosting stack: VPS configuration, security, backups, and uptime monitoring",
        "Cultivated a community with tens of thousands of downloads and ~50,000 monthly visitors",
        "Implemented performance optimizations for fast load times under high traffic",
      ],
      link: "https://frkn64.com",
      caseStudyLink: "#",
      category: ["WordPress", "SEO", "DevOps"],
    },
  ],
  wordpressShowcase: {
    summary:
      "Selected Elementor and WordPress work I built from scratch while working at OctaSys, including client websites, premium theme demos, plugin landing pages, and documentation sites.",
    stats: [
      { value: "40+", label: "Elementor demo sites" },
      { value: "12", label: "Featured live examples" },
      { value: "6+", label: "Industry categories" },
    ],
    sites: [
      {
        title: "Oupi",
        category: "Client Website",
        url: "https://oupistaging.liquid-themes.com/",
        thumbnail: "/images/thumbs/oupi.webp",
        image: "/images/oupi.png",
        role: "Client website for Oupi with Elementor page building, responsive layouts, and visual QA",
        tags: ["WordPress", "Elementor", "Client Website", "Responsive UI"],
      },
      {
        title: "PTM Food",
        category: "Food Brand",
        url: "https://ptmfood.com/",
        thumbnail: "/images/thumbs/ptmfood.webp",
        image: "/images/ptmfood.png",
        role: "Food brand website with Elementor sections, responsive content layout, and launch support",
        tags: ["WordPress", "Elementor", "Responsive UI", "Content Layout"],
      },
      {
        title: "Hotel Suite",
        category: "Hotel",
        url: "https://hotel-suite.liquid-themes.com/",
        thumbnail: "/images/thumbs/hotelsuite.webp",
        image: "/images/hotelsuite.png",
        role: "Premium WordPress theme demo for OctaSys with hospitality page sections, responsive layouts, and visual QA",
        tags: ["WordPress", "Elementor", "Theme Demo", "Hospitality"],
      },
      {
        title: "Asymmetric 9",
        category: "Creative Agency",
        url: "https://asymmetric-9.liquid-themes.com",
        thumbnail: "/images/thumbs/asymmetric9.webp",
        image: "/images/asymmetric9.png",
        role: "Premium WordPress theme demo for OctaSys with agency layouts, portfolio sections, and responsive polish",
        tags: ["WordPress", "Elementor", "Theme Demo", "Portfolio"],
      },
      {
        title: "StartHub One",
        category: "Startup",
        url: "https://starthubone.liquid-themes.com",
        thumbnail: "/images/thumbs/starthub1.webp",
        image: "/images/starthub1.png",
        role: "Premium WordPress theme demo for OctaSys with startup landing sections, reusable blocks, and device checks",
        tags: ["WordPress", "Elementor", "Theme Demo", "Startup"],
      },
      {
        title: "App Blocks Pro",
        category: "SaaS",
        url: "https://appblockspro.liquid-themes.com",
        thumbnail: "/images/thumbs/appblocks.webp",
        image: "/images/appblocks.png",
        role: "Premium WordPress theme demo for OctaSys with SaaS product sections, conversion layouts, and responsive QA",
        tags: ["WordPress", "Elementor", "Theme Demo", "SaaS"],
      },
      {
        title: "Masonry Shop",
        category: "Ecommerce",
        url: "https://masonryshop.liquid-themes.com/",
        thumbnail: "/images/thumbs/masonryshop.webp",
        image: "/images/masonryshop.png",
        role: "Premium WordPress theme demo for OctaSys with ecommerce layouts, product grids, and WooCommerce presentation",
        tags: ["WordPress", "Elementor", "Theme Demo", "WooCommerce"],
      },
      {
        title: "Asymmetric Eight Pro",
        category: "Creative Studio",
        url: "https://asymmetriceightpro.liquid-themes.com",
        thumbnail: "/images/thumbs/asymmetric8.webp",
        image: "/images/asymmetric8.png",
        role: "Premium WordPress theme demo for OctaSys with creative studio sections, portfolio layouts, and visual QA",
        tags: ["WordPress", "Elementor", "Theme Demo", "Creative"],
      },
      {
        title: "Minimalist Arc",
        category: "Architecture",
        url: "https://minimalistarc.liquid-themes.com",
        thumbnail: "/images/thumbs/minimalist.webp",
        image: "/images/minimalist.png",
        role: "Premium WordPress theme demo for OctaSys with architecture layouts, minimalist sections, and responsive polish",
        tags: ["WordPress", "Elementor", "Theme Demo", "Architecture"],
      },
      {
        title: "AI Default",
        category: "AI Product",
        url: "https://aidefault.liquid-themes.com",
        thumbnail: "/images/thumbs/aidefault.webp",
        image: "/images/aidefault.png",
        role: "Premium WordPress theme demo for OctaSys with AI product sections, conversion layouts, and visual QA",
        tags: ["WordPress", "Elementor", "Theme Demo", "AI"],
      },
      {
        title: "BookingHub",
        category: "WordPress Plugin Landing Page",
        url: "https://bookinghub.liquid-themes.com",
        thumbnail: "/images/thumbs/bookinghub.webp",
        image: "/images/bookinghub.png",
        role: "Landing page for OctaSys's WordPress booking plugin project, with product sections, responsive layouts, and visual QA",
        tags: ["WordPress", "Elementor", "Plugin Landing Page", "Responsive UI"],
      },
      {
        title: "BookingHub Docs",
        category: "Documentation Website",
        url: "https://bookinghubdocs.liquid-themes.com/",
        thumbnail: "/images/thumbs/bookinghubdocs.webp",
        image: "/images/bookinghubdocs.png",
        role: "Documentation website for the BookingHub WordPress plugin project, with Elementor, structured content pages, and responsive layouts",
        tags: ["WordPress", "Elementor", "Documentation", "Plugin Docs"],
      },
    ],
  },
  skills: [
    {
      category: "QA & Testing",
      icon: "Shield",
      items: [
        "Manual & automated testing",
        "Test case design",
        "Bug tracking & reporting",
        "Cross-browser & device testing",
        "Performance testing",
      ],
      description: "Ensuring quality at every stage of development",
    },
    {
      category: "WordPress",
      icon: "Blocks",
      items: [
        "Custom theme development",
        "Plugin development",
        "WooCommerce",
        "Performance optimization",
        "Security & maintenance",
      ],
      description: "Building robust WordPress solutions from scratch",
    },
    {
      category: "Frontend",
      icon: "Code2",
      items: [
        "React & Next.js",
        "TypeScript",
        "Tailwind CSS",
        "Responsive design",
        "Accessibility (WCAG)",
      ],
      description: "Creating modern, performant user interfaces",
    },
    {
      category: "AI-Assisted Development",
      icon: "Sparkles",
      items: [
        "Prompt engineering",
        "AI-powered code generation",
        "Workflow automation",
        "Rapid prototyping",
      ],
      description: "Leveraging AI to accelerate development cycles",
    },
    {
      category: "DevOps",
      icon: "Server",
      items: [
        "VPS management (Linux)",
        "Git & version control",
        "PM2 & process management",
        "CDN & caching",
        "Monitoring & logging",
      ],
      description: "Managing infrastructure and deployment pipelines",
    },
    {
      category: "Tools",
      icon: "Wrench",
      items: ["Figma", "VS Code", "Postman", "Chrome DevTools", "GitHub"],
      description: "Equipped with industry-standard tools",
    },
  ],
  navLinks: [
    { href: "#about", label: "About" },
    { href: "#experience", label: "Experience" },
    { href: "#projects", label: "Projects" },
    { href: "#wordpress-showcase", label: "WordPress" },
    { href: "#skills", label: "Skills" },
    { href: "#contact", label: "Contact" },
  ],
  ui: {
    meta: {
      title: "Furkan Ağlar — Portfolio | QA Engineer & Full-Stack Developer",
      description:
        "Portfolio of Furkan Ağlar - QA Engineer, WordPress Developer, and AI-Assisted Full-Stack Developer specializing in Next.js, React, and modern web technologies.",
    },
    hero: {
      availability: "Available for Opportunities",
      ctaPrimary: "Get in Touch",
      ctaSecondary: "LinkedIn",
      scrollHint: "Scroll to explore",
      codeStatusLabel: "status",
      codeStatusValue: "Available",
      codeExperienceLabel: "experience",
      codeYearsLabel: "years",
    },
    about: {
      eyebrow: "// About Me",
      heading: "Building Quality",
      subheading: "Software Solutions",
      whoTitle: "Who I Am",
      whoSubtitle: "Quality-driven developer",
      educationTitle: "Education",
      educationSubtitle: "Academic Background",
      languagesTitle: "Languages",
      languagesSubtitle: "Communication Skills",
      statsYears: "Years of Experience",
      statsProjects: "WordPress Sites & Demos",
      statsSatisfaction: "Client Satisfaction",
    },
    experience: {
      eyebrow: "// Career Journey",
      heading: "Professional",
      subheading: "Experience",
    },
    projects: {
      eyebrow: "// Featured Work",
      heading: "Selected",
      subheading: "Projects",
      filterAll: "All",
      viewProject: "View Project",
      techStack: "Tech Stack",
      categories: "Categories",
      noResults: "No projects found in this category.",
    },
    wordpressShowcase: {
      eyebrow: "// WordPress Portfolio",
      heading: "Elementor",
      subheading: "Demo Sites",
      description:
        "A focused gallery for the WordPress work most relevant to hiring teams looking for Elementor, responsive implementation, and production-ready page building experience.",
      visitSite: "Visit Site",
      placeholder: "Screenshot pending",
      openScreenshot: "Open screenshot",
      fullSizeScreenshot: "Full-size screenshot",
    },
    skills: {
      eyebrow: "// Expertise",
      heading: "Skills &",
      subheading: "Technologies",
      ctaTitle: "Always learning and exploring new technologies",
      ctaSubtitle: "Continuous Growth Mindset",
    },
    contact: {
      eyebrow: "// Get In Touch",
      heading: "Let's Connect",
      description:
        "I'm always open to discussing new projects, opportunities, or collaborations. Feel free to reach out!",
      labels: {
        email: "Email",
        website: "Website",
        linkedin: "LinkedIn",
      },
      visit: "Visit",
      readyTitle: "Ready to start a project?",
      readyBody:
        "Let's discuss how we can work together to bring your ideas to life.",
      sendMessage: "Send a Message",
    },
    footer: {
      blurb:
        "QA Engineer & Full-Stack Developer building quality software solutions with modern technologies.",
      quickLinks: "Quick Links",
      getInTouch: "Get In Touch",
      rights: "All rights reserved.",
      builtWith: "Built with Next.js + TypeScript",
    },
    navbar: {
      cv: "CV",
      downloadCv: "Download CV",
      toggleMenu: "Toggle menu",
    },
    languageToggle: {
      ariaLabel: "Change language",
      options: [
        { code: "en", label: "English", flag: "🇬🇧" },
        { code: "tr", label: "Türkçe", flag: "🇹🇷" },
      ],
    },
    themeToggle: {
      ariaLabel: "Toggle theme",
    },
    copyButton: {
      copy: "Copy",
      copied: "Copied",
      copiedToast: "Copied {label} to clipboard",
      textLabel: "text",
      failed: "Failed to copy",
    },
  },
};

const tr = {
  personalInfo: {
    name: "Furkan Ağlar",
    title: "QA Engineer | WordPress Developer | AI-Assisted Full-Stack Developer",
    location: "Denizli, Türkiye",
    tagline: "Uzaktan çalışmaya ve taşınmaya açık",
    email: "furkan-aglar@outlook.com",
    website: "furkanaglar.com",
    linkedin: "linkedin.com/in/furkanaglar",
    linkedinUrl: "https://linkedin.com/in/furkanaglar",
  },
  quickFacts: ["QA Mühendisi", "WordPress Geliştirici", "Next.js Geliştirici", "DevOps", "Vibe Coder"],
  about: {
    summary:
      "QA Mühendisi ve Full-Stack Geliştirici olarak, kalite güvence uzmanlığı ile uygulamalı geliştirme becerilerini birleştiriyorum. Tasarım konseptlerini yüksek kalite standartlarını koruyarak production'a hazır, rafine uygulamalara dönüştürüyorum. Deneyimim; WordPress tema ve eklenti geliştirme, Next.js gibi modern full-stack framework'ler ve AI destekli geliştirme iş akışlarını kapsıyor.",
    strengths: [
      "QA bakış açısını geliştirme pratiğiyle birleştirerek sorunları production'a ulaşmadan yakalıyorum",
      "Figma'dan production'a sorunsuz bir akış ve piksel hassasiyetinde uygulama",
      "WordPress uzmanlığı: 40+ Elementor demo sitesi, özel temalar, eklentiler, optimizasyon ve kurumsal seviye destek",
      "Hızlı teslimat için AI destekli geliştirme ve prompt engineering",
      "DevOps temelleri: VPS yönetimi, CI/CD, izleme ve altyapı optimizasyonu",
    ],
    education: {
      institution: "Sinop Üniversitesi",
      degree: "İnternet ve Ağ Teknolojileri Bölümü Ön Lisans",
      period: "Eyl 2019 – Haz 2021",
      gpa: "3.62",
    },
    languages: [
      { name: "Türkçe", level: "Ana Dil" },
      { name: "İngilizce", level: "B1" },
      { name: "Almanca", level: "A1" },
    ],
  },
  experience: [
    {
      id: "exp-1",
      title: "QA Engineer & AI-Assisted Software Developer",
      company: "OctaSys",
      location: "Uzaktan",
      period: "Haz 2025 – Şubat 2026",
      achievements: [
        "Web ve mobil uygulamalarda kalite güvence süreçlerine liderlik ederek kritik hataların production'a ulaşmamasını sağladım",
        "Release döngülerini hızlandırmak için otomatik test paketleri geliştirdim ve sürdürdüm",
        "AI destekli iş akışları ve modern framework'lerle full-stack özellikler geliştirdim",
        "Kalite standartlarını ve test stratejilerini belirlemek için çapraz fonksiyonlu ekiplerle çalıştım",
        "Performans, güvenlik ve sürdürülebilirliğe odaklanan kapsamlı code review'lar yaptım",
      ],
    },
    {
      id: "exp-2",
      title: "Project Manager",
      company: "OctaSys",
      location: "Uzaktan",
      period: "Eyl 2024 – Haz 2025",
      achievements: [
        "Birden fazla müşteri projesinde uçtan uca teslimatı yönettim; geliştirme, tasarım ve QA ekiplerini koordine ettim",
        "Agile iş akışları ve sprint planlaması uygulayarak takım hızını %30 artırdım",
        "Müşteriler ile geliştirme ekipleri arasında ana teknik irtibat noktası olarak görev aldım",
        "Eş zamanlı projelerde takvim, bütçe ve kaynak dağılımını yönettim",
        "Dokümantasyon standartları ve bilgi paylaşımı pratikleri oluşturdum",
      ],
    },
    {
      id: "exp-3",
      title: "Frontend WordPress Geliştirici & Destek Mühendisi",
      company: "OctaSys",
      location: "Uzaktan",
      period: "Kas 2021 – Eyl 2024",
      achievements: [
        "SaaS, otel, ecommerce, ajans, mimarlık, AI ürünü ve gıda sektörü kategorilerinde 40+ Elementor tabanlı WordPress demo sitesi ve production sayfası oluşturdum",
        "Figma tasarımlarından 25+ özel WordPress tema ve eklenti geliştirdim, %100 müşteri memnuniyeti sağladım",
        "50+ WordPress sitesine teknik destek vererek karmaşık sorunları 24 saatlik SLA içinde çözdüm",
        "Site performansını optimize ederek 90+ PageSpeed skorları ve 2 saniyenin altında yükleme süreleri elde ettim",
        "SEO best practice'lerini uygulayarak müşteri portföyünde organik trafiği %40 artırdım",
        "Junior geliştiricilere WordPress best practice'leri ve front-end teknolojilerinde mentorluk yaptım",
        "Hosting altyapısı, yedekler, güvenlik güçlendirmesi ve uptime izlemeyi yönettim",
      ],
    },
    {
      id: "exp-4",
      title: "WordPress Developer (Intern)",
      company: "DYT Biyoteknoloji AR-GE",
      location: "Denizli, Türkiye",
      period: "Tem 2021 – Ağu 2021",
      achievements: [
        "Konseptten yayına kadar kurumsal bir WordPress web sitesi tasarlayıp geliştirdim",
        "Paydaşlarla gereksinimleri belirleyip sıkı teslim tarihleri içinde işi tamamladım",
        "WordPress tema özelleştirme ve eklenti entegrasyonu konusunda uygulamalı deneyim kazandım",
      ],
    },
  ],
  projects: [
    {
      id: "proj-1",
      title: "Modsy.io",
      role: "Kurucu & Full-Stack Geliştirici",
      period: "Kas 2025 – Günümüz",
      summary:
        "Oyuncuların özel oyun modifikasyonları oluşturup paylaşabildiği ve indirebildiği bir SaaS platformu. Modern full-stack teknolojilerle geliştirildi ve ilk haftada viral büyüme yakaladı.",
      impact: "İlk haftada 2.500+ indirme",
      stack: [
        "Next.js",
        "React",
        "TypeScript",
        "Node.js",
        "Prisma",
        "MySQL/MariaDB",
        "Tailwind CSS",
        "VPS",
        "Object Storage",
        "CDN",
        "PM2",
        "Git",
        "SEO",
      ],
      highlights: [
        "VPS altyapısında ölçeklenebilir bir full-stack uygulama tasarlayıp yayına aldım",
        "Güvenli kimlik doğrulama, object storage ile dosya yükleme ve CDN entegrasyonu uyguladım",
        "Server-side rendering ve metadata yönetimi ile SEO için optimize ettim",
        "Yayının ilk haftasında 2.500+ indirmeye ulaştı",
      ],
      link: "https://modsy.io",
      caseStudyLink: "#",
      category: ["Next.js", "Full-Stack", "DevOps", "SEO"],
    },
    {
      id: "proj-2",
      title: "Frkn64 Modding",
      role: "Kurucu & WordPress Geliştirici",
      period: "Mar 2016 – Günümüz",
      summary:
        "Nintendo 64 oyun modifikasyonları için topluluk odaklı bir platform. Geliştirme, hosting, performans optimizasyonu ve içerik stratejisi dahil tüm yönlerini yönettim.",
      impact: "Aylık ~50.000 ziyaretçi, on binlerce indirme",
      stack: [
        "WordPress",
        "PHP",
        "MySQL",
        "JavaScript",
        "HTML/CSS",
        "VPS Hosting",
        "Cloudflare CDN",
        "SEO",
      ],
      highlights: [
        "Sıfırdan yüksek trafikli bir WordPress platformu kurup bakımını yaptım",
        "Arama motorları için optimize ederek niş anahtar kelimelerde üst sıralar elde ettim",
        "Tam hosting yığını: VPS yapılandırması, güvenlik, yedekler ve uptime izleme süreçlerini yönettim",
        "On binlerce indirme ve aylık ~50.000 ziyaretçiye sahip bir topluluk oluşturdum",
        "Yüksek trafikte hızlı yükleme süreleri için performans optimizasyonları uyguladım",
      ],
      link: "https://frkn64.com",
      caseStudyLink: "#",
      category: ["WordPress", "SEO", "DevOps"],
    },
  ],
  wordpressShowcase: {
    summary:
      "OctaSys'te çalışırken sıfırdan hazırladığım seçili Elementor ve WordPress çalışmaları: müşteri siteleri, premium tema demoları, eklenti landing page'leri ve dokümantasyon siteleri.",
    stats: [
      { value: "40+", label: "Elementor demo sitesi" },
      { value: "12", label: "Öne çıkan canlı örnek" },
      { value: "6+", label: "Sektör kategorisi" },
    ],
    sites: [
      {
        title: "Oupi",
        category: "Müşteri Web Sitesi",
        url: "https://oupistaging.liquid-themes.com/",
        thumbnail: "/images/thumbs/oupi.webp",
        image: "/images/oupi.png",
        role: "Oupi müşterisi için Elementor sayfa kurulumu, responsive layoutlar ve görsel QA içeren web sitesi",
        tags: ["WordPress", "Elementor", "Müşteri Sitesi", "Responsive UI"],
      },
      {
        title: "PTM Food",
        category: "Gıda Markası",
        url: "https://ptmfood.com/",
        thumbnail: "/images/thumbs/ptmfood.webp",
        image: "/images/ptmfood.png",
        role: "Elementor bölümleri, responsive içerik düzeni ve yayın desteği içeren gıda markası web sitesi",
        tags: ["WordPress", "Elementor", "Responsive UI", "İçerik Düzeni"],
      },
      {
        title: "Hotel Suite",
        category: "Otel",
        url: "https://hotel-suite.liquid-themes.com/",
        thumbnail: "/images/thumbs/hotelsuite.webp",
        image: "/images/hotelsuite.png",
        role: "OctaSys'in premium WordPress teması için otel sayfa bölümleri, responsive layoutlar ve görsel QA içeren demo site",
        tags: ["WordPress", "Elementor", "Tema Demosu", "Otelcilik"],
      },
      {
        title: "Asymmetric 9",
        category: "Kreatif Ajans",
        url: "https://asymmetric-9.liquid-themes.com",
        thumbnail: "/images/thumbs/asymmetric9.webp",
        image: "/images/asymmetric9.png",
        role: "OctaSys'in premium WordPress teması için ajans layoutları, portfolyo bölümleri ve responsive düzenleme içeren demo site",
        tags: ["WordPress", "Elementor", "Tema Demosu", "Portfolyo"],
      },
      {
        title: "StartHub One",
        category: "Startup",
        url: "https://starthubone.liquid-themes.com",
        thumbnail: "/images/thumbs/starthub1.webp",
        image: "/images/starthub1.png",
        role: "OctaSys'in premium WordPress teması için startup landing bölümleri, tekrar kullanılabilir bloklar ve cihaz kontrolleri içeren demo site",
        tags: ["WordPress", "Elementor", "Tema Demosu", "Startup"],
      },
      {
        title: "App Blocks Pro",
        category: "SaaS",
        url: "https://appblockspro.liquid-themes.com",
        thumbnail: "/images/thumbs/appblocks.webp",
        image: "/images/appblocks.png",
        role: "OctaSys'in premium WordPress teması için SaaS ürün bölümleri, dönüşüm odaklı layoutlar ve responsive QA içeren demo site",
        tags: ["WordPress", "Elementor", "Tema Demosu", "SaaS"],
      },
      {
        title: "Masonry Shop",
        category: "Ecommerce",
        url: "https://masonryshop.liquid-themes.com/",
        thumbnail: "/images/thumbs/masonryshop.webp",
        image: "/images/masonryshop.png",
        role: "OctaSys'in premium WordPress teması için ecommerce layoutları, ürün gridleri ve WooCommerce sunumu içeren demo site",
        tags: ["WordPress", "Elementor", "Tema Demosu", "WooCommerce"],
      },
      {
        title: "Asymmetric Eight Pro",
        category: "Kreatif Stüdyo",
        url: "https://asymmetriceightpro.liquid-themes.com",
        thumbnail: "/images/thumbs/asymmetric8.webp",
        image: "/images/asymmetric8.png",
        role: "OctaSys'in premium WordPress teması için kreatif stüdyo bölümleri, portfolyo layoutları ve görsel QA içeren demo site",
        tags: ["WordPress", "Elementor", "Tema Demosu", "Kreatif"],
      },
      {
        title: "Minimalist Arc",
        category: "Mimarlık",
        url: "https://minimalistarc.liquid-themes.com",
        thumbnail: "/images/thumbs/minimalist.webp",
        image: "/images/minimalist.png",
        role: "OctaSys'in premium WordPress teması için mimarlık layoutları, minimalist bölümler ve responsive düzenleme içeren demo site",
        tags: ["WordPress", "Elementor", "Tema Demosu", "Mimarlık"],
      },
      {
        title: "AI Default",
        category: "AI Ürünü",
        url: "https://aidefault.liquid-themes.com",
        thumbnail: "/images/thumbs/aidefault.webp",
        image: "/images/aidefault.png",
        role: "OctaSys'in premium WordPress teması için AI ürün bölümleri, dönüşüm odaklı layoutlar ve görsel QA içeren demo site",
        tags: ["WordPress", "Elementor", "Tema Demosu", "AI"],
      },
      {
        title: "BookingHub",
        category: "WordPress Eklenti Landing Page'i",
        url: "https://bookinghub.liquid-themes.com",
        thumbnail: "/images/thumbs/bookinghub.webp",
        image: "/images/bookinghub.png",
        role: "OctaSys'in WordPress rezervasyon eklentisi projesi için ürün bölümleri, responsive layoutlar ve görsel QA içeren landing page",
        tags: ["WordPress", "Elementor", "Eklenti Landing Page", "Responsive UI"],
      },
      {
        title: "BookingHub Docs",
        category: "Dokümantasyon Web Sitesi",
        url: "https://bookinghubdocs.liquid-themes.com/",
        thumbnail: "/images/thumbs/bookinghubdocs.webp",
        image: "/images/bookinghubdocs.png",
        role: "BookingHub WordPress eklentisi projesi için Elementor, yapılandırılmış içerik sayfaları ve responsive layoutlar içeren dokümantasyon sitesi",
        tags: ["WordPress", "Elementor", "Dokümantasyon", "Eklenti Dokümanı"],
      },
    ],
  },
  skills: [
    {
      category: "QA & Test",
      icon: "Shield",
      items: [
        "Manuel ve otomatik test",
        "Test senaryosu tasarımı",
        "Hata takibi ve raporlama",
        "Çapraz tarayıcı ve cihaz testleri",
        "Performans testleri",
      ],
      description: "Geliştirmenin her aşamasında kaliteyi güvence altına almak",
    },
    {
      category: "WordPress",
      icon: "Blocks",
      items: [
        "Özel tema geliştirme",
        "Eklenti geliştirme",
        "WooCommerce",
        "Performans optimizasyonu",
        "Güvenlik ve bakım",
      ],
      description: "Sıfırdan sağlam WordPress çözümleri oluşturmak",
    },
    {
      category: "Frontend",
      icon: "Code2",
      items: [
        "React & Next.js",
        "TypeScript",
        "Tailwind CSS",
        "Responsive tasarım",
        "Erişilebilirlik (WCAG)",
      ],
      description: "Modern ve performanslı kullanıcı arayüzleri oluşturmak",
    },
    {
      category: "AI Destekli Geliştirme",
      icon: "Sparkles",
      items: [
        "Prompt engineering",
        "AI destekli kod üretimi",
        "İş akışı otomasyonu",
        "Hızlı prototipleme",
      ],
      description: "AI ile geliştirme döngülerini hızlandırmak",
    },
    {
      category: "DevOps",
      icon: "Server",
      items: [
        "VPS yönetimi (Linux)",
        "Git ve sürüm kontrolü",
        "PM2 ve süreç yönetimi",
        "CDN ve önbellekleme",
        "İzleme ve loglama",
      ],
      description: "Altyapı ve deployment pipeline'larını yönetmek",
    },
    {
      category: "Araçlar",
      icon: "Wrench",
      items: ["Figma", "VS Code", "Postman", "Chrome DevTools", "GitHub"],
      description: "Sektör standardı araçlarla donanımlı",
    },
  ],
  navLinks: [
    { href: "#about", label: "Hakkımda" },
    { href: "#experience", label: "Deneyim" },
    { href: "#projects", label: "Projeler" },
    { href: "#wordpress-showcase", label: "WordPress" },
    { href: "#skills", label: "Yetenekler" },
    { href: "#contact", label: "İletişim" },
  ],
  ui: {
    meta: {
      title: "Furkan Ağlar — Portföy | QA Engineer & Full-Stack Developer",
      description:
        "Furkan Ağlar'ın portföyü - Next.js, React ve modern web teknolojilerinde uzmanlaşan QA Engineer, WordPress Developer ve AI-Assisted Full-Stack Developer.",
    },
    hero: {
      availability: "Fırsatlara Açık",
      ctaPrimary: "İletişime Geç",
      ctaSecondary: "LinkedIn",
      scrollHint: "Keşfetmek için kaydır",
      codeStatusLabel: "durum",
      codeStatusValue: "Müsait",
      codeExperienceLabel: "deneyim",
      codeYearsLabel: "yil",
    },
    about: {
      eyebrow: "// Hakkımda",
      heading: "Kalite Odaklı",
      subheading: "Yazılım Çözümleri",
      whoTitle: "Ben Kimim",
      whoSubtitle: "Kalite odaklı geliştirici",
      educationTitle: "Eğitim",
      educationSubtitle: "Akademik Geçmiş",
      languagesTitle: "Diller",
      languagesSubtitle: "İletişim Becerileri",
      statsYears: "Deneyim Yılı",
      statsProjects: "WordPress Siteleri ve Demolar",
      statsSatisfaction: "Müşteri Memnuniyeti",
    },
    experience: {
      eyebrow: "// Kariyer Yolculuğu",
      heading: "Profesyonel",
      subheading: "Deneyim",
    },
    projects: {
      eyebrow: "// Öne Çıkan Çalışmalar",
      heading: "Seçili",
      subheading: "Projeler",
      filterAll: "Tümü",
      viewProject: "Projeyi Gör",
      techStack: "Teknoloji Yığını",
      categories: "Kategoriler",
      noResults: "Bu kategoride proje bulunamadı.",
    },
    wordpressShowcase: {
      eyebrow: "// WordPress Portfolyosu",
      heading: "Elementor",
      subheading: "Demo Siteleri",
      description:
        "Elementor, responsive uygulama ve yayına hazır sayfa kurulum deneyimi arayan işe alım ekipleri için WordPress çalışmalarını öne çıkaran odaklı bir galeri.",
      visitSite: "Siteyi Aç",
      placeholder: "Ekran görüntüsü eklenecek",
      openScreenshot: "Ekran görüntüsünü aç",
      fullSizeScreenshot: "Tam boy ekran görüntüsü",
    },
    skills: {
      eyebrow: "// Uzmanlık",
      heading: "Yetenekler &",
      subheading: "Teknolojiler",
      ctaTitle: "Her zaman yeni teknolojiler öğreniyor ve keşfediyorum",
      ctaSubtitle: "Sürekli Gelişim Zihniyeti",
    },
    contact: {
      eyebrow: "// İletişime Geç",
      heading: "Bağlantı Kuralım",
      description:
        "Yeni projeler, fırsatlar veya iş birlikleri hakkında konuşmaya her zaman açığım. İletişime geçmekten çekinmeyin!",
      labels: {
        email: "E-posta",
        website: "Web Sitesi",
        linkedin: "LinkedIn",
      },
      visit: "Ziyaret Et",
      readyTitle: "Bir projeye başlamaya hazır mısınız?",
      readyBody: "Fikirlerinizi hayata geçirmek için birlikte nasıl çalışabileceğimizi konuşalım.",
      sendMessage: "Mesaj Gönder",
    },
    footer: {
      blurb:
        "QA Engineer & Full-Stack Developer olarak modern teknolojilerle kaliteli yazılım çözümleri üretiyorum.",
      quickLinks: "Hızlı Bağlantılar",
      getInTouch: "İletişime Geç",
      rights: "Tüm hakları saklıdır.",
      builtWith: "Next.js + TypeScript ile geliştirildi",
    },
    navbar: {
      cv: "CV",
      downloadCv: "CV İndir",
      toggleMenu: "Menüyü Aç/Kapat",
    },
    languageToggle: {
      ariaLabel: "Dili değiştir",
      options: [
        { code: "en", label: "İngilizce", flag: "🇬🇧" },
        { code: "tr", label: "Türkçe", flag: "🇹🇷" },
      ],
    },
    themeToggle: {
      ariaLabel: "Temayı değiştir",
    },
    copyButton: {
      copy: "Kopyala",
      copied: "Kopyalandı",
      copiedToast: "{label} panoya kopyalandı",
      textLabel: "metin",
      failed: "Kopyalama başarısız",
    },
  },
};

export const content = { en, tr } as const;
export type Content = typeof en;

export const getContent = (language: Language): Content => {
  return content[language] ?? content.en;
};
