import type { Language } from "./i18n";

const en = {
  personalInfo: {
    name: "Furkan Ağlar",
    title: "WordPress Developer | Product Builder",
    location: "Denizli, Turkiye",
    tagline: "Open to relocation & remote",
    email: "furkan-aglar@outlook.com",
    website: "furkanaglar.com",
    linkedin: "linkedin.com/in/furkanaglar",
    linkedinUrl: "https://linkedin.com/in/furkanaglar",
  },
  quickFacts: [
    "WordPress Specialist",
    "Elementor Expert",
    "WordPress Support Engineer",
    "QA-minded Product Builder",
    "AI-Assisted Developer",
  ],
  about: {
    summary:
      "I am a WordPress Specialist and Elementor-focused WordPress Developer with nearly 10 years of hands-on WordPress experience and 4.5 years of professional experience at OctaSys. My work combines real client website delivery, technical support, QA testing, documentation, hosting operations, and long-term ownership of live web platforms. I am strongest where WordPress, support, quality, and product execution meet.",
    strengths: [
      "Built and customized 50+ WordPress and Elementor websites across client sites, premium theme demos, plugin pages, documentation sites, and personal platforms",
      "Experienced in WordPress troubleshooting, theme customization, plugin configuration, responsive design, maintenance, performance optimization, and SEO",
      "Professional support and QA background: bug reproduction, test cases, issue reporting, documentation, client communication, and release validation",
      "Comfortable managing hosting, Linux servers, deployments, CDN services, backups, security, uptime, and website optimization",
      "Uses Claude Code, Codex, ChatGPT, and AI coding assistants to turn ideas into tested, launched, production-ready products",
    ],
    education: {
      institution: "Sinop University",
      degree: "Associate Degree in Computer Networks and Internet Technologies",
      period: "Sep 2019 - Jun 2021",
      gpa: "3.62",
    },
    languages: [
      { name: "Turkish", level: "Native" },
      { name: "English", level: "B1" },
      { name: "German", level: "A1" },
    ],
  },
  experience: [
    {
      id: "exp-1",
      title: "WordPress Specialist, QA & AI-Assisted Product Builder",
      company: "OctaSys",
      location: "Remote",
      period: "Jun 2025 - Feb 2026",
      achievements: [
        "Combined WordPress delivery experience with QA testing, bug reproduction, release checks, and AI-assisted development workflows",
        "Validated web and product features through manual testing, regression checks, cross-device reviews, and detailed issue reporting",
        "Used AI-assisted coding tools to prototype, test, and ship production-oriented product improvements faster",
        "Created clear documentation for support, QA, product behavior, and implementation details",
        "Worked across development, support, and product coordination tasks to move features from idea to release",
      ],
    },
    {
      id: "exp-2",
      title: "Project Coordinator & Technical Specialist",
      company: "OctaSys",
      location: "Remote",
      period: "Sep 2024 - Jun 2025",
      achievements: [
        "Coordinated client and internal website work across design, development, QA, documentation, and support",
        "Translated requirements into actionable tasks, tracked delivery details, and helped keep releases aligned with business priorities",
        "Acted as a technical bridge between clients, developers, designers, support, and QA stakeholders",
        "Improved handoff quality by clarifying acceptance criteria, documenting edge cases, and following up on implementation details",
        "Supported WordPress, plugin, and product-related decisions with practical knowledge from production websites",
      ],
    },
    {
      id: "exp-3",
      title: "Frontend WordPress Developer & Technical Support Engineer",
      company: "OctaSys",
      location: "Remote",
      period: "Nov 2021 - Sep 2024",
      achievements: [
        "Built and customized 50+ WordPress and Elementor websites, including client websites, premium theme demos, product landing pages, and documentation sites",
        "Created responsive Elementor layouts from design requirements across SaaS, hotel, ecommerce, agency, architecture, AI product, food, and booking categories",
        "Handled WordPress support cases involving themes, plugins, layout issues, performance problems, compatibility bugs, and customer-facing troubleshooting",
        "Performed visual QA, responsive checks, browser testing, bug reproduction, and release validation before websites and demos went live",
        "Worked with HTML, CSS, WordPress admin workflows, theme customization, plugin configuration, hosting environments, backups, CDN, security, and optimization",
        "Produced documentation and support guidance that helped users understand product behavior and resolve common issues faster",
      ],
    },
    {
      id: "exp-4",
      title: "WordPress Developer Intern",
      company: "DYT Biotechnology R&D",
      location: "Denizli, Turkiye",
      period: "Jul 2021 - Aug 2021",
      achievements: [
        "Designed and developed a corporate WordPress website from initial requirements to launch",
        "Customized themes, configured plugins, structured pages, and prepared content for a professional business presence",
        "Gained early hands-on experience with WordPress implementation, client communication, and production website delivery",
      ],
    },
  ],
  projects: [
    {
      id: "proj-1",
      title: "Modsy.io",
      role: "Creator, Product Builder & AI-Assisted Developer",
      period: "Nov 2025 - Present",
      summary:
        "Modsy.io is my flagship technical product: a live SaaS-style platform for game mod sharing built with Next.js, Prisma, and MariaDB. It demonstrates my ability to use AI-assisted development workflows to design, build, test, deploy, and operate a complex real-world platform beyond WordPress.",
      impact: "Production SaaS platform with 2,500+ downloads in the first launch week",
      stack: [
        "Next.js",
        "React",
        "TypeScript",
        "Prisma",
        "MariaDB",
        "Authentication",
        "Role-Based Permissions",
        "Moderation",
        "File Management",
        "VPS",
        "CDN",
        "SEO",
      ],
      highlights: [
        "Designed platform architecture for users, mods, downloads, roles, moderation workflows, and content management",
        "Implemented authentication, role-based permissions, file handling, moderation flows, and admin-oriented product workflows",
        "Managed infrastructure, deployment, database operations, storage, CDN behavior, performance, and production reliability",
        "Used AI-assisted development tools to move from concept to production while validating, testing, refining, and launching the platform",
        "Shows my ability to own a product end to end: idea, architecture, UX, QA, infrastructure, release, and growth",
      ],
      link: "https://modsy.io",
      caseStudyLink: "#",
      category: ["Product", "Next.js", "AI-Assisted", "SaaS", "DevOps"],
    },
    {
      id: "proj-2",
      title: "Frkn64 Modding",
      role: "Founder, WordPress Specialist & Platform Operator",
      period: "Mar 2016 - Present",
      summary:
        "Frkn64 Modding is a long-running WordPress-based community platform for Nintendo 64 game modding. It is the clearest proof of my WordPress depth: I built, maintained, optimized, published, supported, and grew a real content platform serving approximately 50,000 monthly users.",
      impact: "~50,000 monthly users and long-term organic community growth",
      stack: [
        "WordPress",
        "Elementor",
        "PHP",
        "MySQL",
        "HTML/CSS",
        "SEO",
        "Content Publishing",
        "VPS Hosting",
        "Cloudflare CDN",
        "Backups",
        "Security",
        "Performance",
      ],
      highlights: [
        "Built and operated a WordPress platform that has served a niche community for years with consistent content and download workflows",
        "Managed SEO, publishing, WordPress administration, performance optimization, plugin configuration, backups, and security",
        "Grew the platform through search visibility, useful content, community trust, and long-term operational ownership",
        "Handled real production responsibilities including hosting, uptime, troubleshooting, user feedback, and continuous improvement",
        "Demonstrates business impact beyond development: audience growth, platform operations, content strategy, and community management",
      ],
      link: "https://frkn64modding.com",
      caseStudyLink: "#",
      category: ["WordPress", "SEO", "Community", "Platform Operations"],
    },
  ],
  aiDevelopment: {
    summary:
      "I use AI-assisted development as a practical production workflow, not as a shortcut around understanding the product. My process is to define the problem clearly, generate implementation options, inspect and adapt the code, test behavior, reproduce bugs, improve UX, document decisions, and ship working software.",
    points: [
      {
        title: "From Idea to Production",
        description:
          "I can turn product ideas into working applications by combining product thinking, QA discipline, technical support experience, and AI coding tools.",
      },
      {
        title: "Tools I Use",
        description:
          "Claude Code, Codex, ChatGPT, AI coding assistants, GitHub workflows, browser DevTools, documentation, and structured testing.",
      },
      {
        title: "Where It Shows",
        description:
          "Modsy.io is the strongest example: a production platform with authentication, permissions, moderation, file workflows, infrastructure, SEO, and ongoing operations.",
      },
    ],
  },
  wordpressShowcase: {
    summary:
      "Selected WordPress and Elementor work from my time at OctaSys. These projects show hands-on delivery across client websites, premium theme demos, plugin landing pages, documentation sites, responsive layouts, visual QA, and production-ready page building.",
    stats: [
      { value: "50+", label: "WordPress and Elementor builds" },
      { value: "12", label: "Featured live examples" },
      { value: "8+", label: "Business categories" },
    ],
    sites: [
      {
        title: "Oupi",
        category: "Client Website",
        url: "https://oupistaging.liquid-themes.com/",
        thumbnail: "/images/thumbs/oupi.webp",
        image: "/images/oupi.png",
        role: "Client website built with Elementor, responsive page sections, polished visual QA, and launch-ready layout implementation.",
        tags: ["WordPress", "Elementor", "Client Website", "Responsive UI"],
      },
      {
        title: "PTM Food",
        category: "Food Brand",
        url: "https://ptmfood.com/",
        thumbnail: "/images/thumbs/ptmfood.webp",
        image: "/images/ptmfood.png",
        role: "Food brand website focused on clear product presentation, structured content, responsive Elementor layouts, and production launch support.",
        tags: ["WordPress", "Elementor", "Responsive UI", "Content Layout"],
      },
      {
        title: "Hotel Suite",
        category: "Hotel",
        url: "https://hotel-suite.liquid-themes.com/",
        thumbnail: "/images/thumbs/hotelsuite.webp",
        image: "/images/hotelsuite.png",
        role: "Hospitality-focused premium theme demo with room, booking, service, and destination sections built for responsive presentation.",
        tags: ["WordPress", "Elementor", "Theme Demo", "Hospitality"],
      },
      {
        title: "Asymmetric 9",
        category: "Creative Agency",
        url: "https://asymmetric-9.liquid-themes.com",
        thumbnail: "/images/thumbs/asymmetric9.webp",
        image: "/images/asymmetric9.png",
        role: "Creative agency demo built with portfolio storytelling, flexible Elementor sections, responsive polish, and visual consistency checks.",
        tags: ["WordPress", "Elementor", "Theme Demo", "Portfolio"],
      },
      {
        title: "StartHub One",
        category: "Startup",
        url: "https://starthubone.liquid-themes.com",
        thumbnail: "/images/thumbs/starthub1.webp",
        image: "/images/starthub1.png",
        role: "Startup landing experience with reusable Elementor blocks, conversion-focused sections, responsive checks, and launch-ready page structure.",
        tags: ["WordPress", "Elementor", "Theme Demo", "Startup"],
      },
      {
        title: "App Blocks Pro",
        category: "SaaS",
        url: "https://appblockspro.liquid-themes.com",
        thumbnail: "/images/thumbs/appblocks.webp",
        image: "/images/appblocks.png",
        role: "SaaS product demo with feature sections, pricing-style layouts, conversion paths, responsive implementation, and visual QA.",
        tags: ["WordPress", "Elementor", "Theme Demo", "SaaS"],
      },
      {
        title: "Masonry Shop",
        category: "Ecommerce",
        url: "https://masonryshop.liquid-themes.com/",
        thumbnail: "/images/thumbs/masonryshop.webp",
        image: "/images/masonryshop.png",
        role: "Ecommerce theme demo with WooCommerce-style product grids, category presentation, responsive shopping layouts, and polished UI details.",
        tags: ["WordPress", "Elementor", "Theme Demo", "WooCommerce"],
      },
      {
        title: "Asymmetric Eight Pro",
        category: "Creative Studio",
        url: "https://asymmetriceightpro.liquid-themes.com",
        thumbnail: "/images/thumbs/asymmetric8.webp",
        image: "/images/asymmetric8.png",
        role: "Creative studio demo with editorial portfolio sections, Elementor layout composition, responsive behavior checks, and visual QA.",
        tags: ["WordPress", "Elementor", "Theme Demo", "Creative"],
      },
      {
        title: "Minimalist Arc",
        category: "Architecture",
        url: "https://minimalistarc.liquid-themes.com",
        thumbnail: "/images/thumbs/minimalist.webp",
        image: "/images/minimalist.png",
        role: "Architecture-focused demo with minimalist page sections, project presentation, responsive spacing, and carefully checked visual rhythm.",
        tags: ["WordPress", "Elementor", "Theme Demo", "Architecture"],
      },
      {
        title: "AI Default",
        category: "AI Product",
        url: "https://aidefault.liquid-themes.com",
        thumbnail: "/images/thumbs/aidefault.webp",
        image: "/images/aidefault.png",
        role: "AI product landing demo with feature storytelling, conversion-oriented sections, responsive Elementor implementation, and visual QA.",
        tags: ["WordPress", "Elementor", "Theme Demo", "AI"],
      },
      {
        title: "BookingHub",
        category: "WordPress Plugin Landing Page",
        url: "https://bookinghub.liquid-themes.com",
        thumbnail: "/images/thumbs/bookinghub.webp",
        image: "/images/bookinghub.png",
        role: "WordPress plugin landing page presenting product value, booking features, responsive layouts, and user-facing product messaging.",
        tags: ["WordPress", "Elementor", "Plugin Landing Page", "Responsive UI"],
      },
      {
        title: "BookingHub Docs",
        category: "Documentation Website",
        url: "https://bookinghubdocs.liquid-themes.com/",
        thumbnail: "/images/thumbs/bookinghubdocs.webp",
        image: "/images/bookinghubdocs.png",
        role: "Documentation site for a WordPress plugin project, structured for support clarity, searchable content, responsive reading, and product education.",
        tags: ["WordPress", "Elementor", "Documentation", "Plugin Docs"],
      },
    ],
  },
  skills: [
    {
      category: "WordPress & Elementor",
      icon: "Blocks",
      items: [
        "Elementor website building",
        "Theme customization",
        "Plugin configuration",
        "WooCommerce basics",
        "Maintenance and troubleshooting",
      ],
      description: "My primary specialization: building, fixing, optimizing, and maintaining real WordPress websites.",
    },
    {
      category: "HTML, CSS & Responsive UI",
      icon: "Code2",
      items: [
        "HTML and CSS",
        "Responsive layouts",
        "Visual QA",
        "Cross-browser testing",
        "Figma-to-WordPress implementation",
      ],
      description: "Strong front-end fundamentals for polished Elementor and WordPress implementation.",
    },
    {
      category: "Technical Support",
      icon: "Wrench",
      items: [
        "WordPress troubleshooting",
        "Bug reproduction",
        "Customer-facing explanations",
        "Documentation",
        "Issue triage",
      ],
      description: "Support experience that helps users, clients, and teams get to clear, practical resolutions.",
    },
    {
      category: "QA & Testing",
      icon: "Shield",
      items: [
        "Manual testing",
        "Regression checks",
        "Test case design",
        "Bug reports",
        "Release validation",
      ],
      description: "A QA mindset that improves website reliability, product behavior, and release confidence.",
    },
    {
      category: "Hosting & Operations",
      icon: "Server",
      items: [
        "Linux VPS management",
        "Deployments",
        "CDN and caching",
        "Backups and security",
        "Performance optimization",
      ],
      description: "Operational skills for keeping WordPress sites and modern platforms stable in production.",
    },
    {
      category: "AI-Assisted Product Building",
      icon: "Sparkles",
      items: [
        "Claude Code",
        "Codex",
        "ChatGPT",
        "Rapid prototyping",
        "Production iteration",
      ],
      description: "Using AI tools to accelerate development while staying grounded in testing, product quality, and launch reality.",
    },
  ],
  navLinks: [
    { href: "#about", label: "About" },
    { href: "#experience", label: "Experience" },
    { href: "#projects", label: "Projects" },
    { href: "#wordpress-showcase", label: "WordPress" },
    { href: "#ai-development", label: "AI Workflow" },
    { href: "#skills", label: "Skills" },
    { href: "#contact", label: "Contact" },
  ],
  ui: {
    meta: {
      title: "Furkan Ağlar - WordPress Developer & Product Builder",
      description:
        "Portfolio of Furkan Ağlar, a WordPress Specialist and Elementor Expert with nearly 10 years of WordPress experience, technical support, QA, SEO, hosting, and AI-assisted product-building experience.",
    },
    hero: {
      availability: "Available for WordPress, Elementor, Support & Product Roles",
      headline: "WordPress Developer & Product Builder",
      subheadline:
        "I build, customize, troubleshoot, optimize, and maintain WordPress websites while bringing support, QA, hosting, and product ownership experience into the work.",
      proofPoints: [
        { value: "~10", label: "years in WordPress" },
        { value: "50+", label: "WordPress and Elementor builds" },
        { value: "4.5", label: "years of professional work experience" },
      ],
      ctaPrimary: "Discuss an Opportunity",
      ctaSecondary: "LinkedIn",
      scrollHint: "Explore WordPress work",
    },
    about: {
      eyebrow: "// About",
      heading: "WordPress-first",
      subheading: "Technical Specialist",
      whoTitle: "Professional Positioning",
      whoSubtitle: "WordPress, support, QA, and product ownership",
      educationTitle: "Education",
      educationSubtitle: "Technical Foundation",
      languagesTitle: "Languages",
      languagesSubtitle: "Communication",
      statsYears: "Years of WordPress Experience",
      statsProjects: "WordPress and Elementor Builds",
      statsSatisfaction: "Years at OctaSys",
    },
    experience: {
      eyebrow: "// Professional Experience",
      heading: "OctaSys",
      subheading: "and WordPress Delivery",
    },
    projects: {
      eyebrow: "// Product & Platform Work",
      heading: "Real-World",
      subheading: "Case Studies",
      viewProject: "View Project",
      techStack: "Scope & Stack",
      categories: "Positioning",
    },
    wordpressShowcase: {
      eyebrow: "// WordPress Portfolio",
      heading: "Elementor",
      subheading: "Client & Demo Work",
      description:
        "This section is proof of hands-on WordPress delivery: real pages, real layouts, real responsive checks, and practical Elementor execution for different industries and product contexts.",
      visitSite: "Visit Site",
      placeholder: "Screenshot pending",
      openScreenshot: "Open screenshot",
      fullSizeScreenshot: "Full-size screenshot",
    },
    aiDevelopment: {
      eyebrow: "// AI-Assisted Development",
      heading: "From Idea",
      subheading: "to Production",
    },
    skills: {
      eyebrow: "// Core Capabilities",
      heading: "WordPress",
      subheading: "and Technical Skills",
      ctaTitle: "WordPress is my core expertise. Support, QA, operations, and AI-assisted product building make it stronger.",
      ctaSubtitle: "WordPress-first technical specialist",
    },
    contact: {
      eyebrow: "// Contact",
      heading: "Let's Talk",
      description:
        "I am open to WordPress Developer, Elementor Developer, WordPress Specialist, WordPress Support Engineer, Technical Support Engineer, Product Support Engineer, Technical Specialist, startup, and AI-assisted developer roles.",
      labels: {
        email: "Email",
        website: "Website",
        linkedin: "LinkedIn",
      },
      visit: "Visit",
      readyTitle: "Need a WordPress-first technical specialist?",
      readyBody:
        "I can help with WordPress and Elementor delivery, support, QA, website operations, product execution, and AI-assisted development workflows.",
      sendMessage: "Send a Message",
    },
    footer: {
      blurb:
        "WordPress Specialist and Elementor Expert with support, QA, operations, and AI-assisted product-building experience.",
      quickLinks: "Quick Links",
      getInTouch: "Get In Touch",
      rights: "All rights reserved.",
      builtWith: "Built with React + TypeScript",
    },
    navbar: {
      toggleMenu: "Toggle menu",
    },
    themeToggle: {
      ariaLabel: "Toggle theme",
    },
    copyButton: {
      copy: "Copy",
      copied: "Copied",
      copiedToast: "Copied {label} to clipboard",
      textLabel: "text",
      failed: "Failed to copy",
    },
  },
};

export const content = { en } as const;
export type Content = typeof en;

export const getContent = (language: Language): Content => {
  return content[language] ?? content.en;
};
